### ISSUE TITLE
Installation script modifies /dev/tty write permissions

### ISSUE THREAD

**Issue by thomie** [DeterminateSystems/nix-installer#1412]
I installed Nix using the "curl to bash" command from [zero-to-nix](https://zero-to-nix.com/start/install/). After installation, group and other write permissions were removed from `/dev/tty`.  

This is problematic because it prevents SSH from prompting to add unknown hosts to `~/.ssh/known_hosts`, even when `StrictHostKeyChecking ask` is set (the default). As a result, SSH connections to new hosts fail.  

### Steps to reproduce:

Before installation, `/dev/tty` has group and other write permissions:  
```sh
$ ls -l /dev/tty
crw-rw-rw- 1 root tty 5, 0 Feb  5 22:30 /dev/tty
```

Install Nix via the "curl to bash" method:  
```sh
$ curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | \
  sh -s -- install
```

After installation, `/dev/tty` permissions are modified:  
```sh
$ ls -l /dev/tty
crw-r--r-- 1 root tty 5, 0 Feb  5 21:51 /dev/tty
```

Now, group and other no longer have write permissions.  

### Impact: SSH failures  

If `/dev/tty` is not writable, SSH cannot prompt the user to confirm adding an unknown host key, causing authentication failures:  

```sh
$ mv .ssh/known_hosts .ssh/known_hosts.temp

$ sudo chmod o-w /dev/tty

$ ssh -vT git@github.com
...
debug1: read_passphrase: can't open /dev/tty: Permission denied
ssh_askpass: exec(/usr/bin/ssh-askpass): No such file or directory
Host key verification failed.
```

Restoring write permissions resolves the issue:  
```sh
$ sudo chmod o+w /dev/tty

$ ssh -T git@github.com
...
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
...
Hi thomie! ...
```

### Environment:
- **OS:** Ubuntu 24.04  
- **Shell:** Bash  
- **Terminal:** Gnome Terminal  

### Workarounds  

To install Nix without modifying `/dev/tty` permissions, use one of the following methods (both are listed on the [zero-to-nix](https://zero-to-nix.com/start/install/) page):  

1. You can download a binary for the most recent version of the Determinate Nix Installer directly from the [releases](https://github.com/DeterminateSystems/nix-installer/releases) page and run it.

2. You can examine the installation script [here](https://raw.githubusercontent.com/DeterminateSystems/nix-installer/main/nix-installer.sh) then download and run it:
```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix > nix-installer.sh
chmod +x nix-installer.sh
./nix-installer.sh install
```

I confirm that using either workaround preserves `/dev/tty` permissions. It appears that the issue stems from the "curl to bash" installation method.  

**Possibly related:** #813

**Comment by thomie** [comment]
Smaller reproducer:

1. Download `nix-installer-x86_64-linux` from  the [releases](https://github.com/DeterminateSystems/nix-installer/releases) page.

2. Create a file called `nix-installer-1412.sh` containing:
```
#!/bin/sh
./Downloads/nix-installer-x86_64-linux "$@" < /dev/tty
```

3. Run it:
```
$ ./nix-installer-1412.sh  install
```

4. Check `/dev/tty` permissions:
```
$ ls -l /dev/tty
crw-r--r-- 1 root tty 5, 0 Feb  5 21:51 /dev/tty
```

**Comment by cole-h** [comment]
Hm, that _is_ strange.

I haven't tried in an Ubuntu 24.04 VM yet, but on my 22.04 VM, I cannot reproduce using any of your reproducers. I'll be able to take another look tomorrow, but any other information you can provide would be very helpful.

**Comment by thomie** [comment]
I don't fully understand, but it's a combination the function `ensure_root` calling `sudo`, the function `self_test` calling `bash -lc` (which starts a login shell and sources `/root/.profile`), and the (default Ubuntu) `/root/.profile` file containing `mesg n 2> /dev/null || true`. 

Here's another reproducer:
```
sudo mesg n < /dev/tty
```

Changing `-lc` to `-ic` in `src/self_test.rc` fixes it, but there's a comment about Mac requiring `-lc`: 

```
        let mut command = match &self {
            // On Mac, `bash -ic nix` won't work, but `bash -lc nix` will.
            Shell::Sh | Shell::Bash => {
                let mut command = Command::new(executable);
                command.arg("-lc");
                command
            },
            Shell::Zsh | Shell::Fish => {
                let mut command = Command::new(executable);
                command.arg("-ic");
                command
            },
        };
```

**Comment by cole-h** [comment]
Thanks, I can reproduce with that hint now! I'll see if there's a way to work around this (maybe, in the case where we've escalated through sudo, we postpone running the self-tests until afterwards, so that it doesn't pick up the root profile which does the problematic `mesg n`).

**Comment by cole-h** [comment]
I opened https://github.com/DeterminateSystems/nix-installer/pull/1413 which I think should fix this. Once CI finishes, you should be able to test it and double-check that it works for you too:

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/1413 | sh -s -- install
```

**Comment by simongarnier** [comment]
Suffered from the same issue today in Ubuntu 24.04.01 on WSL2, the workaround worked for me as well!

**Comment by thomie** [comment]
That works, but still fails when the user is already root. Perhaps they tried installing something else first and where told to run `sudo su`.

```
sudo su
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/pr/1413 | sh -s -- install
```

I tried changing [`read_line` to read from `/dev/tty` instead of `stdin`](https://github.com/thomie/nix-installer/commit/0389121fb80d92f8d2df7f0e8d08b1ffdd6bccd7). It solves the problem, and allows some code deletion, but would break any script that does `yes | ./nix-installer-x86_64-linux install` among perhaps other problems.

How about https://github.com/DeterminateSystems/nix-installer/pull/1416 instead?

**Comment by cole-h** [comment]
...hah, that's a much more elegant solution. Thanks, I think I'll take that one instead 😆 

(I had assumed that that was already happening, hence my more verbose workaround -- oops!)
