### ISSUE TITLE
Activate shell completion after installation

### ISSUE THREAD

**Issue by matusf** [DeterminateSystems/nix-installer#486]
Hi, thanks for this awesome tool, I use Fedora with SELinux and this installer worked perfectly. 

It would be cool if the installer would activate shell completion. After the completing installation, I should run this command `. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.fish` (or open new shell) to start using nix. I ran the command and could use nix, but the code completion was not working. Then I tried to find out how to add shell completion, but later find out that I need to open a new shell and it will start to work.

OS: Linux
arch: x86_64
nix-installer --version: nix-installer 0.9.0
shell: fish

**Comment by Hoverbear** [comment]
I'll have to take a look and see if we can do that! Thanks.

**Comment by sbellem** [comment]
Completion does not work on my linux machine, even after closing and re-opening a shell.

**Comment by Hoverbear** [comment]
This should be fixed in the next version of nix. :)

**Comment by dwt** [comment]
Sorry to ask here again - but which version of nix do you mean by 'next version'? would that be 2.19.1?

**Comment by IGassmann** [comment]
This still doesn't work for me. I'm on macOS 15.2 (24C101) and just used `curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install` without modifying anything. After installation, I've opened a new terminal session and the completions aren't working for all the shells (fish, zsh and bash).
